[near]
rpc_url = "https://rpc.testnet.near.org"
relayer = "omni-relayer-testnet.testnet"
omni_bridge_id = "omni.n-bridge.testnet"

[eth]
rpc_url = "https://sepolia.infura.io/v3/INFURA_API_KEY"
relayer = "eth:0xae6118F695E078DA03d7c59aD84a6a810D37b707"
# 10 ETH
threshold = "10000000000000000000"

# Base native token is not deployed on testnet
# [base]
# rpc_url = "https://base-sepolia.infura.io/v3/INFURA_API_KEY"
# relayer = "base:0xae6118F695E078DA03d7c59aD84a6a810D37b707"
# # 0.2 ETH
# threshold = "200000000000000000"

# Arb native token is not deployed on testnet
# [arb]
# rpc_url = "https://arbitrum-sepolia.infura.io/v3/INFURA_API_KEY"
# relayer = "arb:0xae6118F695E078DA03d7c59aD84a6a810D37b707"
# # 0.2 ETH
# threshold = "200000000000000000"

[solana]
rpc_url = "https://api.devnet.solana.com"
relayer = "sol:BXss9YNCX2p6VPf2Em54pHXkXnC2FPBeZgbB9fY1cuBR"
# 2 SOL
threshold = "2000000000"
